# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.16

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /workspace/cybercache-cluster

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /workspace/cybercache-cluster

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components

.PHONY : list_install_components/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /workspace/cybercache-cluster/CMakeFiles /workspace/cybercache-cluster/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /workspace/cybercache-cluster/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named man_cybercached.md

# Build rule for target.
man_cybercached.md: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 man_cybercached.md
.PHONY : man_cybercached.md

# fast build rule for target.
man_cybercached.md/fast:
	$(MAKE) -f config/CMakeFiles/man_cybercached.md.dir/build.make config/CMakeFiles/man_cybercached.md.dir/build
.PHONY : man_cybercached.md/fast

#=============================================================================
# Target rules for targets named config

# Build rule for target.
config: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 config
.PHONY : config

# fast build rule for target.
config/fast:
	$(MAKE) -f config/CMakeFiles/config.dir/build.make config/CMakeFiles/config.dir/build
.PHONY : config/fast

#=============================================================================
# Target rules for targets named man_protocol.md

# Build rule for target.
man_protocol.md: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 man_protocol.md
.PHONY : man_protocol.md

# fast build rule for target.
man_protocol.md/fast:
	$(MAKE) -f doc/CMakeFiles/man_protocol.md.dir/build.make doc/CMakeFiles/man_protocol.md.dir/build
.PHONY : man_protocol.md/fast

#=============================================================================
# Target rules for targets named man_command_interface.md

# Build rule for target.
man_command_interface.md: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 man_command_interface.md
.PHONY : man_command_interface.md

# fast build rule for target.
man_command_interface.md/fast:
	$(MAKE) -f doc/CMakeFiles/man_command_interface.md.dir/build.make doc/CMakeFiles/man_command_interface.md.dir/build
.PHONY : man_command_interface.md/fast

#=============================================================================
# Target rules for targets named pp__workspace_cybercache_cluster_tests_server_option_test_cfg

# Build rule for target.
pp__workspace_cybercache_cluster_tests_server_option_test_cfg: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 pp__workspace_cybercache_cluster_tests_server_option_test_cfg
.PHONY : pp__workspace_cybercache_cluster_tests_server_option_test_cfg

# fast build rule for target.
pp__workspace_cybercache_cluster_tests_server_option_test_cfg/fast:
	$(MAKE) -f tests/CMakeFiles/pp__workspace_cybercache_cluster_tests_server_option_test_cfg.dir/build.make tests/CMakeFiles/pp__workspace_cybercache_cluster_tests_server_option_test_cfg.dir/build
.PHONY : pp__workspace_cybercache_cluster_tests_server_option_test_cfg/fast

#=============================================================================
# Target rules for targets named pp__workspace_cybercache_cluster_tests_config_cybercached_test_cfg

# Build rule for target.
pp__workspace_cybercache_cluster_tests_config_cybercached_test_cfg: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 pp__workspace_cybercache_cluster_tests_config_cybercached_test_cfg
.PHONY : pp__workspace_cybercache_cluster_tests_config_cybercached_test_cfg

# fast build rule for target.
pp__workspace_cybercache_cluster_tests_config_cybercached_test_cfg/fast:
	$(MAKE) -f tests/CMakeFiles/pp__workspace_cybercache_cluster_tests_config_cybercached_test_cfg.dir/build.make tests/CMakeFiles/pp__workspace_cybercache_cluster_tests_config_cybercached_test_cfg.dir/build
.PHONY : pp__workspace_cybercache_cluster_tests_config_cybercached_test_cfg/fast

#=============================================================================
# Target rules for targets named pp__workspace_cybercache_cluster_tests_console_test_cfg

# Build rule for target.
pp__workspace_cybercache_cluster_tests_console_test_cfg: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 pp__workspace_cybercache_cluster_tests_console_test_cfg
.PHONY : pp__workspace_cybercache_cluster_tests_console_test_cfg

# fast build rule for target.
pp__workspace_cybercache_cluster_tests_console_test_cfg/fast:
	$(MAKE) -f tests/CMakeFiles/pp__workspace_cybercache_cluster_tests_console_test_cfg.dir/build.make tests/CMakeFiles/pp__workspace_cybercache_cluster_tests_console_test_cfg.dir/build
.PHONY : pp__workspace_cybercache_cluster_tests_console_test_cfg/fast

#=============================================================================
# Target rules for targets named c3lib_ce

# Build rule for target.
c3lib_ce: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 c3lib_ce
.PHONY : c3lib_ce

# fast build rule for target.
c3lib_ce/fast:
	$(MAKE) -f lib/c3lib/CMakeFiles/c3lib_ce.dir/build.make lib/c3lib/CMakeFiles/c3lib_ce.dir/build
.PHONY : c3lib_ce/fast

#=============================================================================
# Target rules for targets named comp_brotli

# Build rule for target.
comp_brotli: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 comp_brotli
.PHONY : comp_brotli

# fast build rule for target.
comp_brotli/fast:
	$(MAKE) -f lib/compression/brotli/CMakeFiles/comp_brotli.dir/build.make lib/compression/brotli/CMakeFiles/comp_brotli.dir/build
.PHONY : comp_brotli/fast

#=============================================================================
# Target rules for targets named comp_lz4

# Build rule for target.
comp_lz4: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 comp_lz4
.PHONY : comp_lz4

# fast build rule for target.
comp_lz4/fast:
	$(MAKE) -f lib/compression/lz4/CMakeFiles/comp_lz4.dir/build.make lib/compression/lz4/CMakeFiles/comp_lz4.dir/build
.PHONY : comp_lz4/fast

#=============================================================================
# Target rules for targets named comp_lzf

# Build rule for target.
comp_lzf: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 comp_lzf
.PHONY : comp_lzf

# fast build rule for target.
comp_lzf/fast:
	$(MAKE) -f lib/compression/lzf/CMakeFiles/comp_lzf.dir/build.make lib/compression/lzf/CMakeFiles/comp_lzf.dir/build
.PHONY : comp_lzf/fast

#=============================================================================
# Target rules for targets named comp_lzham

# Build rule for target.
comp_lzham: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 comp_lzham
.PHONY : comp_lzham

# fast build rule for target.
comp_lzham/fast:
	$(MAKE) -f lib/compression/lzham/CMakeFiles/comp_lzham.dir/build.make lib/compression/lzham/CMakeFiles/comp_lzham.dir/build
.PHONY : comp_lzham/fast

#=============================================================================
# Target rules for targets named comp_snappy

# Build rule for target.
comp_snappy: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 comp_snappy
.PHONY : comp_snappy

# fast build rule for target.
comp_snappy/fast:
	$(MAKE) -f lib/compression/snappy/CMakeFiles/comp_snappy.dir/build.make lib/compression/snappy/CMakeFiles/comp_snappy.dir/build
.PHONY : comp_snappy/fast

#=============================================================================
# Target rules for targets named comp_zlib

# Build rule for target.
comp_zlib: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 comp_zlib
.PHONY : comp_zlib

# fast build rule for target.
comp_zlib/fast:
	$(MAKE) -f lib/compression/zlib/CMakeFiles/comp_zlib.dir/build.make lib/compression/zlib/CMakeFiles/comp_zlib.dir/build
.PHONY : comp_zlib/fast

#=============================================================================
# Target rules for targets named comp_zstd

# Build rule for target.
comp_zstd: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 comp_zstd
.PHONY : comp_zstd

# fast build rule for target.
comp_zstd/fast:
	$(MAKE) -f lib/compression/zstd/CMakeFiles/comp_zstd.dir/build.make lib/compression/zstd/CMakeFiles/comp_zstd.dir/build
.PHONY : comp_zstd/fast

#=============================================================================
# Target rules for targets named hash_farmhash

# Build rule for target.
hash_farmhash: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 hash_farmhash
.PHONY : hash_farmhash

# fast build rule for target.
hash_farmhash/fast:
	$(MAKE) -f lib/hashes/farmhash/CMakeFiles/hash_farmhash.dir/build.make lib/hashes/farmhash/CMakeFiles/hash_farmhash.dir/build
.PHONY : hash_farmhash/fast

#=============================================================================
# Target rules for targets named hash_murmurhash

# Build rule for target.
hash_murmurhash: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 hash_murmurhash
.PHONY : hash_murmurhash

# fast build rule for target.
hash_murmurhash/fast:
	$(MAKE) -f lib/hashes/murmurhash/CMakeFiles/hash_murmurhash.dir/build.make lib/hashes/murmurhash/CMakeFiles/hash_murmurhash.dir/build
.PHONY : hash_murmurhash/fast

#=============================================================================
# Target rules for targets named hash_spookyhash

# Build rule for target.
hash_spookyhash: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 hash_spookyhash
.PHONY : hash_spookyhash

# fast build rule for target.
hash_spookyhash/fast:
	$(MAKE) -f lib/hashes/spookyhash/CMakeFiles/hash_spookyhash.dir/build.make lib/hashes/spookyhash/CMakeFiles/hash_spookyhash.dir/build
.PHONY : hash_spookyhash/fast

#=============================================================================
# Target rules for targets named hash_xxhash

# Build rule for target.
hash_xxhash: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 hash_xxhash
.PHONY : hash_xxhash

# fast build rule for target.
hash_xxhash/fast:
	$(MAKE) -f lib/hashes/xxhash/CMakeFiles/hash_xxhash.dir/build.make lib/hashes/xxhash/CMakeFiles/hash_xxhash.dir/build
.PHONY : hash_xxhash/fast

#=============================================================================
# Target rules for targets named regex_pcre2

# Build rule for target.
regex_pcre2: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 regex_pcre2
.PHONY : regex_pcre2

# fast build rule for target.
regex_pcre2/fast:
	$(MAKE) -f lib/regex/pcre2/CMakeFiles/regex_pcre2.dir/build.make lib/regex/pcre2/CMakeFiles/regex_pcre2.dir/build
.PHONY : regex_pcre2/fast

#=============================================================================
# Target rules for targets named epoll

# Build rule for target.
epoll: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 epoll
.PHONY : epoll

# fast build rule for target.
epoll/fast:
	$(MAKE) -f src/utils/epoll/CMakeFiles/epoll.dir/build.make src/utils/epoll/CMakeFiles/epoll.dir/build
.PHONY : epoll/fast

#=============================================================================
# Target rules for targets named hesper

# Build rule for target.
hesper: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 hesper
.PHONY : hesper

# fast build rule for target.
hesper/fast:
	$(MAKE) -f src/utils/hesper/CMakeFiles/hesper.dir/build.make src/utils/hesper/CMakeFiles/hesper.dir/build
.PHONY : hesper/fast

#=============================================================================
# Target rules for targets named pcre2

# Build rule for target.
pcre2: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 pcre2
.PHONY : pcre2

# fast build rule for target.
pcre2/fast:
	$(MAKE) -f src/utils/pcre2/CMakeFiles/pcre2.dir/build.make src/utils/pcre2/CMakeFiles/pcre2.dir/build
.PHONY : pcre2/fast

#=============================================================================
# Target rules for targets named regex

# Build rule for target.
regex: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 regex
.PHONY : regex

# fast build rule for target.
regex/fast:
	$(MAKE) -f src/utils/regexp/CMakeFiles/regex.dir/build.make src/utils/regexp/CMakeFiles/regex.dir/build
.PHONY : regex/fast

#=============================================================================
# Target rules for targets named ext_cybercache

# Build rule for target.
ext_cybercache: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ext_cybercache
.PHONY : ext_cybercache

# fast build rule for target.
ext_cybercache/fast:
	$(MAKE) -f src/client/CMakeFiles/ext_cybercache.dir/build.make src/client/CMakeFiles/ext_cybercache.dir/build
.PHONY : ext_cybercache/fast

#=============================================================================
# Target rules for targets named cybercache

# Build rule for target.
cybercache: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 cybercache
.PHONY : cybercache

# fast build rule for target.
cybercache/fast:
	$(MAKE) -f src/console/CMakeFiles/cybercache.dir/build.make src/console/CMakeFiles/cybercache.dir/build
.PHONY : cybercache/fast

#=============================================================================
# Target rules for targets named cybercached_ce

# Build rule for target.
cybercached_ce: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 cybercached_ce
.PHONY : cybercached_ce

# fast build rule for target.
cybercached_ce/fast:
	$(MAKE) -f src/server/CMakeFiles/cybercached_ce.dir/build.make src/server/CMakeFiles/cybercached_ce.dir/build
.PHONY : cybercached_ce/fast

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... install/strip"
	@echo "... install/local"
	@echo "... install"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... man_cybercached.md"
	@echo "... config"
	@echo "... man_protocol.md"
	@echo "... man_command_interface.md"
	@echo "... pp__workspace_cybercache_cluster_tests_server_option_test_cfg"
	@echo "... pp__workspace_cybercache_cluster_tests_config_cybercached_test_cfg"
	@echo "... pp__workspace_cybercache_cluster_tests_console_test_cfg"
	@echo "... c3lib_ce"
	@echo "... comp_brotli"
	@echo "... comp_lz4"
	@echo "... comp_lzf"
	@echo "... comp_lzham"
	@echo "... comp_snappy"
	@echo "... comp_zlib"
	@echo "... comp_zstd"
	@echo "... hash_farmhash"
	@echo "... hash_murmurhash"
	@echo "... hash_spookyhash"
	@echo "... hash_xxhash"
	@echo "... regex_pcre2"
	@echo "... epoll"
	@echo "... hesper"
	@echo "... pcre2"
	@echo "... regex"
	@echo "... ext_cybercache"
	@echo "... cybercache"
	@echo "... cybercached_ce"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

